### ISSUE TITLE
Swift 4 upgrade

### ISSUE THREAD

**Issue by vaggos666** [michaeldorner/ByteBackpacker#4]
Swift 4 reports: Static let 'nativeByteOrder' is internal and cannot be referenced from a default argument value.

Any workaround?

**Comment by michaeldorner** [comment]
Thanks for pointing out! I will have a look today.

**Comment by vaggos666** [comment]
Great. My temporary workaround was the following. In case it helps.

Added an extra case .notspecified and then in the functions added and extra control.

public enum ByteOrder {
    case bigEndian
    case littleEndian
    **case notSpecified**    
     /// Machine specific byte order
    static let nativeByteOrder: ByteOrder = (Int(CFByteOrderGetCurrent()) == Int(CFByteOrderLittleEndian.rawValue)) ? .littleEndian : .bigEndian
}

open class func unpack<T: Any>(_ valueByteArray: [Byte], **byte_Order: ByteOrder = .notSpecified**) -> T {
        //assert(!(type(of: T.self) is AnyObject), referenceTypeErrorString) // does not work in Swift 3
        
        **let byteOrder: ByteOrder = (byte_Order == .notSpecified) ? .nativeByteOrder : byte_Order**
        
        let bytes = (byteOrder == .littleEndian) ? valueByteArray : valueByteArray.reversed()
        return bytes.withUnsafeBufferPointer {
            return $0.baseAddress!.withMemoryRebound(to: T.self, capacity: 1) {
                $0.pointee
            }
        }
    }

**Comment by michaeldorner** [comment]
I think it is a [bug in Swift 4](https://bugs.swift.org/browse/SR-5111).

**Comment by michaeldorner** [comment]
And fixed it with [version 1.2](https://github.com/michaeldorner/ByteBackpacker/releases/tag/1.2). :) 
I just made it `public`.
