### ISSUE TITLE
Cocoapods repo out of date

### ISSUE THREAD

**Issue by sashahilton00** [michaeldorner/ByteBackpacker#7]
Hi,

Just logging this issue as the version currently in Cocoapods is 1.1.1 as opposed to 1.2, which means the slightly irritating issue of changing ```static let nativeByteOrder``` to ```public static let nativeByteOrder``` is present. It would be great if we could get a new version pushed to CocoaPods. Thanks for the library :)

**Comment by michaeldorner** [comment]
Thank you for your issue report. Indeed, there was an error in the .podspec, which I fixed in version 1.2.1. Sorry, my bad. :-)

**Comment by sashahilton00** [comment]
Cheers for that
