### ISSUE TITLE
withMemoryRebound

### ISSUE THREAD

**Issue by DanijelHuis** [michaeldorner/ByteBackpacker#8]
Hi, I am interested in this line:
`Array(UnsafeBufferPointer(start: $0.withMemoryRebound(to: Byte.self, capacity: 1){$0}, count: MemoryLayout<T>.size))`

As I can see you are returning pointer from withMemoryRebound body closure and using it externally. Is this safe? I am asking because while reading docs I found this:

> A closure that takes a typed pointer to the same memory as this pointer, only bound to type T. **The closure’s pointer argument is valid only for the duration of the closure’s execution**.
https://developer.apple.com/documentation/swift/unsafepointer/2430863-withmemoryrebound

I didn't encounter any error or anything, just learning about all this UnsafePointer and MemoryLayout stuff so I am sorry if I misunderstood something.

**Comment by michaeldorner** [comment]
Thanks for your remark and hint! I think it is safe, because it is the argument, not the memory which is only valid for the duration of the execution. 
Do you have another solution in mind?

**Comment by DanijelHuis** [comment]
OK but what I meant, you are using that argument (pointer) after execution of closure is finished. If you look at the code below, that is how I thought it should be - reboundPointer is used only inside its closure, it is not returned from that closure and then used outside, isn't that what that quote talks about?

 I am still trying to figure out this typed/raw memory stuff so I might be wrong, your code works of course.

 ```
open class func pack<T: Any>( _ value: T, byteOrder: ByteOrder = .nativeByteOrder) -> [Byte]
    {
        var value = value // inout works only for var not let types
        let valueByteArray = withUnsafePointer(to: &value)
        {
            return $0.withMemoryRebound(to: Byte.self, capacity: 1)
            {
                reboundPointer -> [Byte] in

                return Array(UnsafeBufferPointer(start: reboundPointer, count: MemoryLayout<T>.size))
            }
        }
        
        return (byteOrder == ByteOrder.nativeByteOrder) ? valueByteArray : valueByteArray.reversed()
    }
```

**Comment by michaeldorner** [comment]
@DanijelHuis Did you got any further insights during your research?
